<?php


namespace Palasthotel\WordPress\BlockX\Widgets;


use Palasthotel\WordPress\BlockX\Model\Option;

class Select extends _Widget {

	const TYPE = "select";

	private $options = [];

	public static function build(string $key, string $label, string $defaultValue = ""){
		return new static($key, $label, static::TYPE, $defaultValue );
	}

	/**
	 * @param Option[] $options
	 *
	 * @return Select
	 */
	public function setOptions(array $options){
		$this->options = $options;
		return $this;
	}

	public function toArray() {
		$arr = parent::toArray(); // TODO: Change the autogenerated stub
		$arr["options"] = $this->options;
		return $arr;
	}

}