<?php


namespace Palasthotel\WordPress\BlockX\Widgets;


use Palasthotel\WordPress\BlockX\Model\Option;

class TaxQuery extends _Widget {

	const TYPE = "tax_query";

	/**
	 * @var string[]
	 */
	private $taxonomies;

	/**
	 * TaxQuery constructor.
	 *
	 * @param string $key
	 * @param string $label
	 * @param Option[] $taxonomies
	 * @param array $defaultValue
	 */
	public function __construct( string $key, string $label, $taxonomies, $defaultValue = [] ) {
		parent::__construct( $key, $label, static::TYPE, $defaultValue );
		$this->taxonomies = $taxonomies;
	}

	/**
	 * @param string $key
	 * @param string $label
	 * @param Option[] $taxonomies
	 * @param array $defaultValue
	 *
	 * @return TaxQuery
	 */
	public static function build(string $key, string $label, array $taxonomies, array $defaultValue = []){
		return new static($key, $label, $taxonomies, $defaultValue);
	}

	public function toArray() {
		$arr = parent::toArray(); // TODO: Change the autogenerated stub
		$arr["taxonomies"] = $this->taxonomies;
		return $arr;
	}
}