<?php


namespace Palasthotel\WordPress\BlockX\ContentStructure;


class ListOf extends _Item {

	const TYPE = "list_of";

	/**
	 * @var ContentStructure
	 */
	private $contentStructure;

	/**
	 * ListOf constructor.
	 *
	 * @param string $key
	 * @param string $title
	 * @param _Item[] $contentStructure
	 */
	public function __construct( string $key, string $title, array $contentStructure ) {
		parent::__construct( $key, $title, static::TYPE );
		$this->contentStructure = new ContentStructure($contentStructure);
	}

	/**
	 * @return ContentStructure
	 */
	public function contentStructure(){
		return $this->contentStructure;
	}

	/**
	 * @return array
	 */
	public function toArray() {
		$arr = parent::toArray(); // TODO: Change the autogenerated stub
		$arr["contentStructure"] = $this->contentStructure()->toArray();
		return $arr;
	}

}